#!/bin/bash

source spinner;

THIS=$$;
ME="$(basename $0)";

DATA_DIR=${HOME}/rtl_sigint
RAW_DIR=${DATA_DIR}/raw

mkdir -p ${RAW_DIR}


duration=120
scan_type="default"
verbose=false
log=false
logfile="/tmp/rtl_sigint.log"
network=true

if ! options=$(getopt -u -n "$ME" -o d:t:nvl -l duration:,type:,no-network,verbose,log -- "$@")
then
	exit 1
fi

set -- $options

while [ $# -gt 0 ]
do
    case $1 in
    -d|--duration) duration="$2" ; shift;;
    -n|--no-network) network=false ;;
    -t|--type) scan_type="$2" ; shift;;
    -v|--verbose) verbose=true ;;
    -l|--log) log=true ;;
    (--) shift; break;;
    (-*) echo "$0: error - unrecognized option $1" 1>&2; exit 1;;
    (*) break;;
    esac
    shift
done

PIDS=$(pgrep -d" " $ME);
for PID in $PIDS
do
	[[ "$PID" -ne "$THIS" ]] && kill -9 -"$PID";
done

RED='\033[1;31m'
GREEN='\033[1;32m'
ORANGE='\033[1;33m'
NC='\033[0m' # No Color


printf "${GREEN}Scanning 433MHz for short range devices for $duration seconds"
mkdir -p ${RAW_DIR}/rtl_433
(rtl_433 -T $duration -G -F json:${RAW_DIR}/rtl_433/433.json >/dev/null 2>&1;) &
spinner $!
printf "\n${ORANGE}Detected N signals from X devices.${NC} \n"

printf "${GREEN}Scanning 868MHz for short range devices for $duration seconds"
mkdir -p ${RAW_DIR}/rtl_433
(rtl_433 -T $duration -f 868M -G -F json:${RAW_DIR}/rtl_433/869M.json >/dev/null 2>&1;) &
spinner $!
printf "\n${ORANGE}Detected N signals from X devices.${NC} \n"


